# secrets-template.yaml
# DO NOT put real credentials here!
# Use kubectl commands below instead

---
# AWS Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
# Created with: kubectl create secret generic aws-credentials --from-file=...

---
# Snowflake Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: insurance-iq-secrets
type: Opaque
stringData:
  snowflake-account: "YOUR_ACCOUNT"
  snowflake-user: "YOUR_USER"
  snowflake-password: "YOUR_PASSWORD"
  snowflake-warehouse: "COMPUTE_WH"
  snowflake-database: "INSURANCE_IQ"
  snowflake-schema: "CLAIMS_DATA"
  snowflake-role: "ACCOUNTADMIN"
# Created with: kubectl create secret generic insurance-iq-secrets --from-env-file=...